services:
  # MySQL Database for Testing
  mysql-test:
    image: mysql:8.0
    container_name: story-teller-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: testroot123
      MYSQL_DATABASE: storyteller_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - '${TEST_MYSQL_HOST_PORT:-3307}:3306' # Different port to avoid conflicts
    networks:
      - test-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis for Testing Celery Integration (optional profile)
  redis-test:
    image: redis:7-alpine
    container_name: story-teller-redis-test
    restart: unless-stopped
    ports:
      - '${TEST_REDIS_HOST_PORT:-6380}:6379' # Different port to avoid conflicts with dev Redis
    command: redis-server --appendonly no # No persistence for tests
    networks:
      - test-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    profiles: ['celery', 'full']

networks:
  test-network:
    driver: bridge
