version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: story-teller-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-storyteller}
      MYSQL_USER: ${MYSQL_USER:-storyteller_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-storyteller_pass}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - story-teller-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # FastAPI Application
  app:
    build: .
    container_name: story-teller-app
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: mysql+mysqlconnector://${MYSQL_USER:-storyteller_user}:${MYSQL_PASSWORD:-storyteller_pass}@mysql:3306/${MYSQL_DATABASE:-storyteller}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-storyteller}
      MYSQL_USER: ${MYSQL_USER:-storyteller_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-storyteller_pass}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - story-teller-network
    volumes:
      - ./logs:/app/logs

  # phpMyAdmin (optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: story-teller-phpmyadmin
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-storyteller_user}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-storyteller_pass}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - story-teller-network

volumes:
  mysql_data:
    driver: local

networks:
  story-teller-network:
    driver: bridge
