version: '3.8'

services:
  # MySQL Database for Testing
  mysql-test:
    image: mysql:8.0
    container_name: story-teller-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: testroot123
      MYSQL_DATABASE: storyteller_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - '3307:3306' # Different port to avoid conflicts
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - test-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_test_data:
    driver: local

networks:
  test-network:
    driver: bridge
